# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kladaba', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='ects',
            field=models.IntegerField(default=3),
        ),
    ]
