# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kladaba', '0002_lecture_ects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='ects',
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
    ]
